#ifdef F90TESTWRAPPERS
      interface PREPENDF90( CONCAT2(LEVEL,WHAT,_))
#ifdef HAVECINT
        GTESTFUNCTION(LEVEL,WHAT,integer,C_INT,NAME1,NAME2)

        GTESTFUNCTIONM(LEVEL,WHAT,integer,C_INT,NAME1,NAME2)
#endif
#ifdef HAVECFLOAT
        GTESTFUNCTION(LEVEL,WHAT,real,C_FLOAT,NAME1,NAME2)

        GTESTFUNCTIONM(LEVEL,WHAT,real,C_FLOAT,NAME1,NAME2)
#endif
#ifdef HAVECDOUBLE
        GTESTFUNCTION(LEVEL,WHAT,real,C_DOUBLE,NAME1,NAME2)

        GTESTFUNCTIONM(LEVEL,WHAT,real,C_DOUBLE,NAME1,NAME2)
#endif
#ifdef HAVECBOOL
        GTESTFUNCTION(LEVEL,WHAT,logical,C_BOOL,NAME1,NAME2)

        GTESTFUNCTIONM(LEVEL,WHAT,logical,C_BOOL,NAME1,NAME2)
#endif
#ifdef DOSTR
        GTESTFUNCTION(LEVEL,WHAT,NAME1,NAME2)
        GTESTFUNCTIONM(LEVEL,WHAT,NAME1,NAME2)
#endif

      end interface PREPENDF90( CONCAT2(LEVEL,WHAT,_))
#endif