#ifdef F90TESTWRAPPERS
      interface PREPENDF90( CONCAT3(BOOST,LEVEL,WHAT,_))
#ifdef HAVECINT
        BOOSTFUNCTION(LEVEL,WHAT,integer,C_INT,NAME1,NAME2)
#endif
#ifdef HAVECFLOAT
        BOOSTFUNCTION(LEVEL,WHAT,real,C_FLOAT,NAME1,NAME2)
#endif
#ifdef HAVECDOUBLE
        BOOSTFUNCTION(LEVEL,WHAT,real,C_DOUBLE,NAME1,NAME2)
#endif
#ifdef HAVECBOOL
        BOOSTFUNCTION(LEVEL,WHAT,logical,C_BOOL,NAME1,NAME2)
#endif
      end interface PREPENDF90( CONCAT3(BOOST,LEVEL,WHAT,_))
#endif